import { DataTypes, Model, Sequelize } from "@contact/sequelize";
export const name = "User";
export const model = (sequelize: Sequelize) => {
  class model extends Model {}
  model.init(
    {
      id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
      login: { type: DataTypes.VARCHAR(32) },
      password: { type: DataTypes.VARCHAR(64) },
      f: { type: DataTypes.VARCHAR(32) },
      i: { type: DataTypes.VARCHAR(32) },
      o: { type: DataTypes.VARCHAR(32) },
      r_role_id: { type: DataTypes.INTEGER },
      block_flag: { type: DataTypes.INTEGER },
      dsc: { type: DataTypes.VARCHAR(128) },
      depart: { type: DataTypes.VARCHAR(16) },
      int_num: { type: DataTypes.VARCHAR(32) },
      mob_num: { type: DataTypes.VARCHAR(128) },
      r_timetable_id: { type: DataTypes.INTEGER },
      r_department_id: { type: DataTypes.INTEGER },
      depart_status: { type: DataTypes.INTEGER },
      position: { type: DataTypes.VARCHAR(128) },
      rank: { type: DataTypes.INTEGER },
      win_user_name: { type: DataTypes.VARCHAR(32) },
      work_num: { type: DataTypes.VARCHAR(128) },
      prom_trans: { type: DataTypes.INTEGER },
      filial: { type: DataTypes.INTEGER },
      r_collection_plan_id: { type: DataTypes.INTEGER },
      dt1$: { type: DataTypes.DATE },
      mail_sign: { type: DataTypes.VARCHAR(256) },
      agent_id: { type: DataTypes.VARCHAR(32) },
      agent_number: { type: DataTypes.VARCHAR(32) },
      is_virtual: { type: DataTypes.INTEGER },
      start_work_date: { type: DataTypes.DATE },
      oper_id: { type: DataTypes.INTEGER },
      email: { type: DataTypes.VARCHAR(64) },
      emp_number: { type: DataTypes.VARCHAR(32) },
      password_change_dt: { type: DataTypes.DATE },
      finish_work_date: { type: DataTypes.DATE },
      agent_pass: { type: DataTypes.VARCHAR(32) },
      agent_name: { type: DataTypes.VARCHAR(32) },
      sid: { type: DataTypes.VARCHAR(38) },
      sid_dt: { type: DataTypes.DATE },
      work_address: { type: DataTypes.VARCHAR(256) },
      work_zip_code: { type: DataTypes.VARCHAR(32) },
      latitude: { type: DataTypes.NUMERIC(18, 6) },
      longitude: { type: DataTypes.NUMERIC(18, 6) },
      skill: { type: DataTypes.INTEGER },
      R_DEPARTMENT_ID2: { type: DataTypes.INTEGER },
      SKIN: { type: DataTypes.INTEGER },
      typ: { type: DataTypes.INTEGER },
      r_person_anket_id: { type: DataTypes.INTEGER },
      room: { type: DataTypes.STRING(16) },
      DICT_VALUE_1: { type: DataTypes.INTEGER },
      LANG: { type: DataTypes.INTEGER },
      AGENT_KEY: { type: DataTypes.STRING(128) },
      AGENT_TOKEN: { type: DataTypes.STRING(1024) },
      AGENT_SERVER_TYPE: { type: DataTypes.VARCHAR(64) },
      CHANGE_DT: { type: DataTypes.DATE },
      EXT_ID$: { type: DataTypes.STRING(64) },
    },
    {
      sequelize,
      modelName: "User",
      tableName: "users",
      createdAt: false,
      updatedAt: "CHANGE_DT",
    }
  );
  return Model;
};
